### ISSUE TITLE
Version constraint to payum/core

### ISSUE THREAD

**Issue by dpfaffenbauer** [Payum/OmnipayV3Bridge#2]
Hi,

wouldn't it be good idea to change the version constraint in v3-bridge from 

```
"payum/core": "^1.3"
```

to

```
"payum/core": "^1.4.3"
```

as well?

**Comment by makasim** [comment]
@dpfaffenbauer indeed

**Comment by dpfaffenbauer** [comment]
should I provide a PR?

**Comment by makasim** [comment]
done 9f56f4f5d8761cbd1229b23d4787dde7aa567dde
